about_item/urls.py
from django.contrib import admin 
from django.urls import include, path 
from about_item import views

app_name = "about_item"

urlpatterns = [
    path('', views.index, name='home'),
    path('post_data/', views.post_data, name='post_data'),
    path('get_history_data/', views.get_history_data, name='get_history_data'),
    path('get_model_data/', views.get_model_data, name='get_model_data'),
]

etropi/urls.py
from django.contrib import admin
from django.urls import path, include
from cek_item import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('cek_item/',include('cek_item.urls')),
    path('about_item/',include('about_item.urls')),
    path('cek_peta/', include('fathinah.urls')),
    path('compare_item/', include('compare_item.urls')),
    path('profile/', include('profile.urls')),

]

about_item/models.py
from django.db import models
from rest_framework import serializers

def keep_last_24(MyModel):
	most_recents = MyModel.objects.all()
	if(len(most_recents)>24):
		last24 = MyModel.objects.all()[len(most_recents) - 24:]
		MyModel.objects.exclude(id__in=last24).delete()

class UploadModel(models.Model):
	
	objectphoto = models.TextField(default = "")
	material = models.CharField(max_length = 15)
	price = models.PositiveIntegerField()
	year = models.CharField(max_length = 6)

	class meta:
		ordering = ['id']

	def save(self, *args, **kwargs):

		super(UploadModel, self).save(*args, **kwargs)

		keep_last_24(UploadModel)

# class untuk serialize secara rekursif. 
# sumber: https://ruddra.com/posts/django-serialize-foreignkey-m2m-property-instance-fields/ 
class DataSerializer(serializers.ModelSerializer):
	class Meta:
		model = UploadModel
		fields = "__all__"
		depth = 1

about_item/forms.py
from django import forms

class UploadForm(forms.Form):
	
	data = forms.CharField(label="Image link of item you want to check")

about_item/views.py
from .forms import UploadForm
from .models import UploadModel, DataSerializer
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect

import random
import json
import time
import requests
from PIL import Image
from io import BytesIO

material_selection = ["Leather", "Cotton", "Nylon", "Canvas", "Straw", "Denim", "Neoprene", "Mesh"]

year_selection = [str(x) for x in range(2010, 2020)]

# cek apakah link image valid
# sumber: https://stackoverflow.com/questions/11261210/django-check-if-an-image-exists-at-some-particular-url
def valid_image_link(link):

	try:

		response = requests.get(link)
		img = Image.open(BytesIO(response.content))
		img.verify()
		return True

	except:
		return False

def post_data(request): 
	if request.is_ajax() and request.method == 'POST':
		json_data = json.loads(request.body)
		objectphoto = json_data['data']

		# ngecek kevalalidan link image
		if(not valid_image_link(objectphoto)):
			response = JsonResponse({'message': "Invalid image link!"})
			response.status_code = 400
			return response

		data = UploadModel(objectphoto = json_data['data'],
						   material = random.sample(material_selection, 1)[0],
						   price = random.randint(100000, 10000000),
						   year = random.sample(year_selection, 1)[0])
		
		data.save()

		# simpan data ini ke history jika usernya login
		if request.user.is_authenticated:
			current_user = User.objects.get(username=request.user.username)
			new_history = current_user.userhistory_set.create(operation_name="About Item", 
															  objectphoto = json_data['data'])

		# ubah data ini ke json lalu balikin
		serializer = DataSerializer(data)
		serialized = serializer.data

		return JsonResponse(serialized, safe=False)

def get_history_data(request): 
	if request.is_ajax():

		serializer = DataSerializer(UploadModel.objects.all(), many=True)
		serialized = serializer.data

		time.sleep(2)

		return JsonResponse(serialized, safe=False)


def get_model_data(request): 
	if request.is_ajax():
		obj_id = request.GET.get('obj_id', '')
		
		# cari model dengan id obj_id
		if(obj_id!=''):

			queried = UploadModel.objects.filter(id=obj_id)
			serializer = DataSerializer(queried, many=True)
			time.sleep(2)

			return JsonResponse(serializer.data, safe=False)

def index(request):
	context = {'app' : 'about_item'}
	form  = UploadForm()
	context['form'] = form
	return render(request, 'about_item/index.html', context)

templates/about_item/index.html
{% extends 'general/base.html' %}
{% load static %}

{% block title %}About item{% endblock %}

{% block customCss %}
<link rel="stylesheet" href="{% static 'about_item/css/about_item.css' %}">
<script src="{% static 'about_item/js/edit_content.js' %}"></script>
<script src="{% static 'general/js/history.js' %}"></script>
<script src="{% static 'about_item/js/about_item.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container mid">
    <div class="row mid-ver height">
        <div class="mid col">
            <form id="submit_form" enctype="multipart/form-data" action="{% url 'about_item:post_data' %}" method="post">
                <br>
                <br>
                <br>
                {% csrf_token %}
                <br>
                <br>
                {{ form.as_p }}
                <br>

                <button id="submit_button" class="button" type="submit" class="btn">Upload</button>
                <br>
                <hr>
            </form>
        </div>
    </div>

    <img src="{% static 'cek_item/assets/loading.gif' %}" id="loading_content" class="mx-auto" style="display: none;">
    <div id="content" style="display: none;">
        <br>
        <div class="row mid-ver height">          
            <div class="mid col">
                <h3 class="udr"> Details </h3>
                <span><img id="image" class="bag-img preview_photo"></span>
                <br>
	   			<h4>Material : <span id="material_data"></span></h4>
	   			<h4>Price : Rp.<span id="price_data"></span></h4>
	   			<h4>Year Released : <span id="year_data"></span></h4>
	   		</div>
	   		<hr>
        </div>

        <br>
        <hr>
    </div>
</div>

{% endblock %}