about_item/urls.py
from django.contrib import admin 
from django.urls import include, path 
from about_item import views

app_name = "about_item"

urlpatterns = [
    path('', views.index, name='home'),
    path('post_data/', views.post_data, name='post_data'),
    path('get_history_data/', views.get_history_data, name='get_history_data'),
    path('get_model_data/', views.get_model_data, name='get_model_data'),
]

cek_item/urls.py
from django.contrib import admin 
from . import views
from django.urls import path, include

app_name = "cek_item"

urlpatterns = [
    path('', views.index, name='home'),
    path('post_data/', views.post_data, name='post_data'),
    path('get_history_data/', views.get_history_data, name='get_history_data'),
    path('get_model_data/', views.get_model_data, name='get_model_data'),
]

etropi/urls.py
from django.contrib import admin
from django.urls import path, include
from cek_item import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('cek_item/',include('cek_item.urls')),
    path('about_item/',include('about_item.urls')),
    path('cek_peta/', include('fathinah.urls')),
    path('compare_item/', include('compare_item.urls')),
    path('profile/', include('profile.urls')),

]

fathinah/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cek_peta'

urlpatterns = [
    path('', views.index, name='home'),
    path('post_data/', views.post_data, name='post_data'),
    path('get_history_data/', views.get_history_data, name='get_history_data'),
    path('get_model_data/', views.get_model_data, name='get_model_data'),

]

profile/urls.py
from django.contrib import admin 
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from profile.forms import CustomAuthForm

app_name = "profile"

urlpatterns = [
	
    path('login/', auth_views.LoginView.as_view(template_name='profile/login.html', authentication_form=CustomAuthForm, 
    											extra_context={"app":"profile"}, redirect_authenticated_user=True), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='profile:login'), name = 'logout'),
    path('register/', views.register_user, name="register"),
    path('history/', views.history, name="history"),
]

templates/general/base.html
{% load static %}
{% load filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="{% static 'general/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'general/css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'general/css/navbar.css' %}">

    <script src="{% static 'general/js/jquery.min.js' %}"></script>
    <script src="{% static 'general/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'general/js/bootstrap.min.js' %}"></script>

    
    {% block customCss %}

    {% endblock %}
    
    <title>{% block title %}{% endblock %}</title>
    
    {% url ':get_model_data'|prepend:app as model_url %}
    {% if model_url %}
        <div id="model_get_from" data="{{ model_url }}">
    {% endif %}

</head>
<body>
    <nav class="navbar navbar-light navbar-expand-lg sticky-top navbar-custom mb-4">
        <div class="container">
            <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand mr-auto" href="#">E-TROPI</a>
            
            <div class="d-flex flex-row order-2 order-md-3">
             <div class="navbar-nav flex-row">
                {% if user.is_authenticated %}    
                  <a class="nav-item nav-link" id="username-header" href="{% url 'profile:history' %}">
                    {{ user.username }}
                  </a>

                  <span class="navbar-btn ml-2" id="auth_button">
                      <a href="{% url 'profile:logout' %}" class="btn">Logout</a>
        
                  </span>
                {% else %}
                  <span class="navbar-text" id="username-header">
                    Guest
                  </span>

                  <span class="navbar-btn ml-2" id="auth_button">
                      <a href="{% url 'profile:login' %}" class="btn">Login</a>
                  </span>
                {% endif %}
                
              </div>
            </div>
            <div class="collapse navbar-collapse order-3 order-md-2" id="navbarNav">
                <div class="navbar-nav">

                    <a class="nav-item nav-link" href="{% url 'cek_item:home' %}">CHECK ITEM</a>
                    <a class="nav-item nav-link" href="{% url 'cek_peta:home' %}">COUNTRY FROM</a>
                    <a class="nav-item nav-link" href="{% url 'about_item:home' %}">ABOUT ITEM</a>
                    <a class="nav-item nav-link" href="{% url 'compare_item:home' %}">COMPARE ITEM</a>
                    
                </div>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

    {% ifnotequal app "profile" %}
        <div class="container mx-auto">
            <div class="row mb-3">
                <h1 class="udr">History</h1>
            </div>

            <div class="row">
                <img src="{% static 'cek_item/assets/loading.gif' %}" id="loading_history" class="mx-auto" style="display: none;">
            </div>

            <div class="row" id="history_content">

            </div>
        </div>

    
        {% url ':get_history_data'|prepend:app as history_url %}
        {% if history_url %}
          <script>load_history( "{{ history_url }}" )</script>
        {% endif %}
    {% endifnotequal %}


</body>
</html>