cek_item/urls.py
from django.contrib import admin 
from . import views
from django.urls import path, include

app_name = "cek_item"

urlpatterns = [
    path('', views.index, name='home'),
    path('post_data/', views.post_data, name='post_data'),
    path('get_history_data/', views.get_history_data, name='get_history_data'),
    path('get_model_data/', views.get_model_data, name='get_model_data'),
]

etropi/urls.py
from django.contrib import admin
from django.urls import path, include
from cek_item import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('cek_item/',include('cek_item.urls')),
    path('about_item/',include('about_item.urls')),
    path('cek_peta/', include('fathinah.urls')),
    path('compare_item/', include('compare_item.urls')),
    path('profile/', include('profile.urls')),

]

cek_item/models.py
from django.db import models
from rest_framework import serializers


# hanya menyimpan 24 elemen terakhir
def keep_last_24(MyModel):
    most_recents = MyModel.objects.all()
    if (len(most_recents) > 24):
        last24 = MyModel.objects.all()[len(most_recents) - 24:]
        MyModel.objects.exclude(id__in=last24).delete()


class CelebrityPhoto(models.Model):
    name = models.TextField(max_length=20, default="", primary_key=True)
    photo = models.TextField(default="")

    class meta:
        verbose_name_plural = "celebrity photos"


class Data(models.Model):
    celebrities = models.ManyToManyField(CelebrityPhoto)
    objectphoto = models.TextField(default="")
    genuine = models.BooleanField(default="")

    class meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        super(Data, self).save(*args, **kwargs)

        keep_last_24(Data)


# class untuk serialize secara rekursif. 
# sumber: https://ruddra.com/posts/django-serialize-foreignkey-m2m-property-instance-fields/ 
class DataSerializer(serializers.ModelSerializer):
    class Meta:
        model = Data
        fields = "__all__"
        depth = 1

cek_item/forms.py
from django import forms


class DataForm(forms.Form):
	
	data = forms.CharField(label="Image link of item you want to check")

cek_item/views.py
from django.shortcuts import render, redirect
from .models import Data, CelebrityPhoto, DataSerializer
from .forms import DataForm
from django.http import JsonResponse
import random
import json
import time
from django.contrib.auth.models import User
import requests
from PIL import Image
from io import BytesIO


# import http.client as http
def landing_page(request):
    return redirect('cek_item:home')


# pilih 8 foto random untuk setiap objek
def populate_celebs(data):
    selected = CelebrityPhoto.objects.order_by('?')[:8]
    for celeb in selected:
        data.celebrities.add(celeb)


# cek apakah link image valid
# sumber: https://stackoverflow.com/questions/11261210/django-check-if-an-image-exists-at-some-particular-url
def valid_image_link(link):
    try:

        response = requests.get(link)
        img = Image.open(BytesIO(response.content))
        img.verify()
        return True

    except:
        return False


def post_data(request):
    if request.is_ajax() and request.method == 'POST':

        json_data = json.loads(request.body)
        objectphoto = json_data['data']

        # ngecek kevalalidan link image
        if (not valid_image_link(objectphoto)):
            response = JsonResponse({'message': "Invalid image link!"})
            response.status_code = 400
            return response

        # menentukan apakah barang asli atau palsu secara random (50%)
        genuine = True
        num = random.random()
        if (num > 0.5):
            genuine = False

        data = Data(genuine=genuine,
                    objectphoto=json_data['data'])

        data.save()  # harus di save kalau mau masukin ManytoMany
        populate_celebs(data)
        data.save()

        # simpan data ini ke history jika usernya login
        if request.user.is_authenticated:
            current_user = User.objects.get(username=request.user.username)
            new_history = current_user.userhistory_set.create(operation_name="Check Item",
                                                              objectphoto=json_data['data'])

        # ubah data ini ke json lalu balikin
        serializer = DataSerializer(data)
        serialized = serializer.data

        return JsonResponse(serialized, safe=False)


def get_history_data(request):
    if request.is_ajax():
        serializer = DataSerializer(Data.objects.all(), many=True)
        serialized = serializer.data

        time.sleep(2)

        return JsonResponse(serialized, safe=False)


def get_model_data(request):
    if request.is_ajax():
        obj_id = request.GET.get('obj_id', '')

        # cari model dengan id obj_id
        if (obj_id != ''):
            queried = Data.objects.filter(id=obj_id)
            serializer = DataSerializer(queried, many=True)
            time.sleep(2)

            return JsonResponse(serializer.data, safe=False)


def index(request):
    context = {'app': 'cek_item'}
    form = DataForm()
    context['form'] = form
    return render(request, 'cek_item/index.html', context)

templates/cek_item/index.html
{% extends "general/base.html" %}
{% load static %}

{% block title %}Check Item{% endblock %}

{% block customCss %}
<link rel="stylesheet" href="{% static 'cek_item/css/cek_item.css' %}">
<script src="{% static 'cek_item/js/edit_content.js' %}"></script>
<script src="{% static 'general/js/history.js' %}"></script>
<script src="{% static 'cek_item/js/cek_item.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container mid">
    <div class="row mid-ver height">
        <form id="submit_form" enctype="multipart/form-data" action="{% url 'cek_item:post_data' %}" method="post">
            <br>
            <br>
            <br>
            {% csrf_token %}
            <br>
            <br>
            {{ form.as_p }}
            <br>
            <br>

            <button id="submit_button" class="button" type="submit" class="btn">Upload</button>
        </form>
        <hr>
    </div>

    <img src="{% static 'cek_item/assets/loading.gif' %}" id="loading_content" class="mx-auto" style="display: none;">
    <div id="content" style="display: none;">

        <div class="row mid-ver height">
            <div class="mid loc">
                <h3 class="udr"> Your Item </h3>
                <span><img id="image" class="bag-img preview_photo" ></span>
            </div>

            <div class="mid"><h3>The item is <span id="genuine_desc"></span></h3></div>


        </div>


        <div id="celebs" class="row mid-ver height" style="display: none">

            <div class="mid mb-3"><h3 class="udr">The item is also used by </h3>
            </div>
            <br/>

            <div class="row" id="celeb_photos">
            </div>

        </div>

    </div>

</div>

{% endblock %}