compare_item/urls.py
from django.urls import path, include
from compare_item import views

app_name="compare_item"

urlpatterns = [
    path('', views.index, name="home"),
    path('post_data/', views.compare_item, name="compare"),
    path('get_history_data/', views.get_history_data, name="get_history_data"),
    path('get_model_data/', views.get_model_data, name="get_model_data")
]

etropi/urls.py
from django.contrib import admin
from django.urls import path, include
from cek_item import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('cek_item/',include('cek_item.urls')),
    path('about_item/',include('about_item.urls')),
    path('cek_peta/', include('fathinah.urls')),
    path('compare_item/', include('compare_item.urls')),
    path('profile/', include('profile.urls')),

]

compare_item/models.py
from django.db import models
from rest_framework import serializers

# Create your models here.
def save_last_24(AnyModel):
    recents = AnyModel.objects.all()
    if(len(recents)>24):
        last_24 = AnyModel.objects.all()[len(recents) - 24:]
        AnyModel.objects.exclude(id__in=last_24).delete()

class Data(models.Model):
    objectphoto = models.TextField(default = "")
    Genuine = models.BooleanField(default="")
    Brand = models.CharField(max_length=15)
    Price = models.PositiveIntegerField()
    Release_date = models.PositiveIntegerField()
    Location = models.CharField(max_length=20)

    class meta:
        ordering = ['id']

    def save(self, *args, **kwargs):
        super(Data, self).save(*args, **kwargs)
        save_last_24(Data)

# class untuk serialize secara rekursif. 
# sumber: https://ruddra.com/posts/django-serialize-foreignkey-m2m-property-instance-fields/ 
class DataSerializer(serializers.ModelSerializer):

    class Meta:
        model = Data
        fields = "__all__"
        depth = 1
        

compare_item/forms.py
from django import forms

class DataForm(forms.Form):
    ObjectPhoto = forms.CharField(label="Image link of item you want to check")

compare_item/views.py
from django.shortcuts import render, reverse, redirect
from .forms import DataForm
from .models import Data, DataSerializer
from django.http import JsonResponse
import random
import json
import time
from django.contrib.auth.models import User
import requests
from PIL import Image
from io import BytesIO
# Create your views here.

def index(request):
    context = {'app':'compare_item'}
    context['form'] = DataForm()
    context['history'] = Data.objects.all()
    return render(request, "compare_item/index.html", context)


# cek apakah link image valid
# sumber: https://stackoverflow.com/questions/11261210/django-check-if-an-image-exists-at-some-particular-url
def valid_image_link(link):
    try:
        response = requests.get(link)
        img = Image.open(BytesIO(response.content))
        img.verify()
        return True
    except:
        return False

def compare_item(request):
    if(request.is_ajax() and request.method == "POST"):
        json_data = json.loads(request.body)
        objectphoto = json_data['data']
        print(objectphoto)
        # ngecek kevalalidan link image
        if(not valid_image_link(objectphoto)):
            response = JsonResponse({'message': "Invalid image link!"})
            response.status_code = 400
            return response
        
        genuine = True
        list_brand = ["Gucci", "H&M", "Hermes", "Uniqlo", "Zara", "Adidas", "Chanel", "Burberry", "Prada", "Levi's"]
        list_location = ["Singapore", "America", "Canada", "Germany"]
        release_date = random.randrange(1999,2019)
        price = random.randrange(150,2000)
        brand = list_brand[random.randrange(9)]
        location = list_location[random.randrange(4)]
        num = random.random()
        print(num)
        if(num>0.5):
            genuine = False

        data_item = Data(Genuine=genuine, objectphoto=json_data['data'], Brand=brand,Release_date=release_date,Price=price,Location=location)
        data_item.save()

        # simpan data ini ke history jika usernya login
        if request.user.is_authenticated:
                current_user = User.objects.get(username=request.user.username)
                new_history = current_user.userhistory_set.create(operation_name="Compare Item", objectphoto = json_data['data'])

        serializer = DataSerializer(data_item)
        serialized = serializer.data

        time.sleep(2)
        
        return JsonResponse(serialized, safe=False)

def get_history_data(request):
    if request.is_ajax():
    
        serializer = DataSerializer(Data.objects.all(), many=True)
        serialized = serializer.data

        time.sleep(2)

        return JsonResponse(serialized, safe=False)

# tidak dihitung di coverage karena sudah di functional test
def get_model_data(request):

    if request.is_ajax():
        obj_id = request.GET.get('obj_id', '')
        
        # cari model dengan id obj_id
    if(obj_id!=''):

        queried = Data.objects.filter(id=obj_id)
        serializer = DataSerializer(queried, many=True)
        time.sleep(2)

        return JsonResponse(serializer.data, safe=False)

templates/compare_item/index.html
{% extends 'general/base.html' %}
{% load static %}

{% block title %}Compare item{% endblock %}

{% block customCss %}
<link rel="stylesheet" href="{% static 'compare_item/style.css' %}">
<script src="{% static 'compare_item/script.js' %}"></script>
<script src="{% static 'general/js/history.js' %}"></script>
{% endblock %}

{% block content %}
	<section class="compare block" >
        <div class="row">
            <div class="col-md-12 form">
                {% if not form %}
                    NO FORM
                {% endif %}
                <form id="submit_form" enctype="multipart/form-data" action="{% url 'compare_item:compare' %}" method="post">
                    {% csrf_token %}
	   	        	{{ form.as_p }}
	   		        <button id="submit_button" type="submit" class="btn">Compare!</button>
	   	        </form>
            </div>
        </div>

        <img src="{% static 'cek_item/assets/loading.gif' %}" id="loading_content" class="mx-auto" style="display: none;">
        <div id="content" style="display:none">

            <div class="row">
                <div class="col-md-12">
                    <h3>Original Item</span></h3>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span><img id="img1" class="bag-img preview_photo" ></span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h3>The item is <span id="genuine_desc"></span>!</h3>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span><img id="img2" class="bag-img preview_photo" ></span>
                </div>
            </div>
            
                <div class="details row show-item" style="display: none;">
                    <div class="col-md-3">
                        <h4><strong>Brand</strong></h4>
                        <p id="brand"></p>
                    </div>
                    <div class="col-md-3">
                        <h4><strong>Price</strong></h4>
                        <p id="price"></p>
                    </div>
                    <div class="col-md-3">
                        <h4><strong>Release Date</strong></h4>
                        <p id="date"></p>
                    </div>
                    <div class="col-md-3">
                        <h4><strong>Location</strong></h4>
                        <p id="location"></p>
                    </div>          
                </div>
        </div>
                
        
        <div class="row">
            <div class="col-md-12 check-other">
                <a href="{% url 'compare_item:home' %}"><button type="button" class="btn btn-outline-primary">COMPARE OTHER ITEM</button></a>
            </div>
        </div>
    </section>
{% endblock %}